### ISSUE TITLE
Segmentation fault on Void Linux

### ISSUE THREAD

**Issue by ernierasta** [atomnuker/wlstream#10]
Hi!
It segfaults on my system I suspect, that wlstream makes some assumptions about environment? Maybe some check at compile time would help?

here is full [`strace` log](https://gist.github.com/ernierasta/20759018475d865451eee02051a74cb9).

Btw: [wl-recorder](https://github.com/ammen99/wf-recorder) works ok on my system.

**Comment by ernierasta** [comment]
@atomnuker is this maintained? And I am not asking about this issue, but there are PRs waiting, what is never good for community to keep interest ...

**Comment by atomnuker** [comment]
Sorry, I don't really want to work on this anymore.
I've left the WIP code I've written in the new_code branch. It worked better audio-wise IIRC, back in July, but I started abstracting the video capture part, didn't commit when it worked and it turned out was way more work than something I'd consider fun.
Someone else can pick it up if they feel like it.
